=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CacheRestApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CacheRestApiApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CacheRestApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CacheRestApiApi' do
    it 'should create an instance of CacheRestApiApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CacheRestApiApi)
    end
  end

  # unit tests for api_v1_cachekey_invalidate_post
  # Takes a list of datasources, finds the associated cache records and invalidates them and removes the database records
  # @param body A list of datasources uuid or the tuples of database and datasource names
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_cachekey_invalidate_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
