=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CurrentUserApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CurrentUserApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CurrentUserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrentUserApi' do
    it 'should create an instance of CurrentUserApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CurrentUserApi)
    end
  end

  # unit tests for api_v1_me_get
  # Returns the user object corresponding to the agent making the request, or returns a 401 error if the user is unauthenticated.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20035]
  describe 'api_v1_me_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
