=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DashboardPermanentLinkApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DashboardPermanentLinkApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DashboardPermanentLinkApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DashboardPermanentLinkApi' do
    it 'should create an instance of DashboardPermanentLinkApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DashboardPermanentLinkApi)
    end
  end

  # unit tests for api_v1_dashboard_permalink_key_get
  # Retrives dashboard state associated with a permanent link.
  # @param key 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20015]
  describe 'api_v1_dashboard_permalink_key_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_dashboard_pk_permalink_post
  # Stores a new permanent link.
  # @param body 
  # @param pk 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2017]
  describe 'api_v1_dashboard_pk_permalink_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
