=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ExploreFormDataApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExploreFormDataApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ExploreFormDataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExploreFormDataApi' do
    it 'should create an instance of ExploreFormDataApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ExploreFormDataApi)
    end
  end

  # unit tests for api_v1_explore_form_data_key_delete
  # Deletes a form_data.
  # @param key The form_data key.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20024]
  describe 'api_v1_explore_form_data_key_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_explore_form_data_key_get
  # Retrives a form_data.
  # @param key 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20032]
  describe 'api_v1_explore_form_data_key_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_explore_form_data_key_put
  # Updates an existing form_data.
  # @param body 
  # @param key 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :tab_id 
  # @return [InlineResponse20110]
  describe 'api_v1_explore_form_data_key_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_explore_form_data_post
  # Stores a new form_data.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :tab_id 
  # @return [InlineResponse20110]
  describe 'api_v1_explore_form_data_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
