=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FilterSetRestApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FilterSetRestApiApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FilterSetRestApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FilterSetRestApiApi' do
    it 'should create an instance of FilterSetRestApiApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FilterSetRestApiApi)
    end
  end

  # unit tests for api_v1_dashboard_dashboard_id_filtersets_get
  # Get a dashboard&#x27;s list of filter sets
  # @param dashboard_id The id of the dashboard
  # @param [Hash] opts the optional parameters
  # @return [Array<InlineResponse20016>]
  describe 'api_v1_dashboard_dashboard_id_filtersets_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_dashboard_dashboard_id_filtersets_pk_delete
  # Deletes a Dashboard.
  # @param dashboard_id 
  # @param pk 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse400]
  describe 'api_v1_dashboard_dashboard_id_filtersets_pk_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_dashboard_dashboard_id_filtersets_pk_put
  # Changes a Dashboard&#x27;s Filter set.
  # @param body Filter set schema
  # @param dashboard_id 
  # @param pk 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20017]
  describe 'api_v1_dashboard_dashboard_id_filtersets_pk_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_dashboard_dashboard_id_filtersets_post
  # Create a new Dashboard&#x27;s Filter Set.
  # @param body Filter set schema
  # @param dashboard_id The id of the dashboard
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2015]
  describe 'api_v1_dashboard_dashboard_id_filtersets_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
