=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::LogRestApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LogRestApiApi' do
  before do
    # run before each test
    @instance = SwaggerClient::LogRestApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LogRestApiApi' do
    it 'should create an instance of LogRestApiApi' do
      expect(@instance).to be_instance_of(SwaggerClient::LogRestApiApi)
    end
  end

  # unit tests for api_v1_log_get
  # Get a list of models
  # @param [Hash] opts the optional parameters
  # @option opts [GetListSchema] :q 
  # @return [InlineResponse20033]
  describe 'api_v1_log_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_log_pk_get
  # Get an item model
  # @param pk 
  # @param [Hash] opts the optional parameters
  # @option opts [GetItemSchema] :q 
  # @return [InlineResponse20034]
  describe 'api_v1_log_pk_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_log_post
  # @param body Model schema
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20112]
  describe 'api_v1_log_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
