=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MenuApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MenuApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MenuApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MenuApi' do
    it 'should create an instance of MenuApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MenuApi)
    end
  end

  # unit tests for api_v1_menu_get
  # Get the menu data structure. Returns a forest like structure with the menu the user has access to
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20036]
  describe 'api_v1_menu_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
