=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::OpenApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OpenApiApi' do
  before do
    # run before each test
    @instance = SwaggerClient::OpenApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OpenApiApi' do
    it 'should create an instance of OpenApiApi' do
      expect(@instance).to be_instance_of(SwaggerClient::OpenApiApi)
    end
  end

  # unit tests for api_version_openapi_get
  # Get the OpenAPI spec for a specific API version
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'api_version_openapi_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
