=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ReportSchedulesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReportSchedulesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ReportSchedulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportSchedulesApi' do
    it 'should create an instance of ReportSchedulesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ReportSchedulesApi)
    end
  end

  # unit tests for api_v1_report_delete
  # Deletes multiple report schedules in a bulk operation.
  # @param [Hash] opts the optional parameters
  # @option opts [GetDeleteIdsSchema] :q 
  # @return [InlineResponse400]
  describe 'api_v1_report_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_get
  # Get a list of report schedules, use Rison or JSON query parameters for filtering, sorting, pagination and for selecting specific columns and metadata.
  # @param [Hash] opts the optional parameters
  # @option opts [GetListSchema] :q 
  # @return [InlineResponse20039]
  describe 'api_v1_report_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_info_get
  # Get metadata information about this API resource
  # @param [Hash] opts the optional parameters
  # @option opts [GetInfoSchema] :q 
  # @return [InlineResponse2001]
  describe 'api_v1_report_info_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_pk_delete
  # Delete a report schedule
  # @param pk The report schedule pk
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse400]
  describe 'api_v1_report_pk_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_pk_get
  # Get a report schedule
  # @param pk 
  # @param [Hash] opts the optional parameters
  # @option opts [GetItemSchema] :q 
  # @return [InlineResponse20040]
  describe 'api_v1_report_pk_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_pk_log_get
  # Get a list of report schedule logs, use Rison or JSON query parameters for filtering, sorting, pagination and for selecting specific columns and metadata.
  # @param pk The report schedule id for these logs
  # @param [Hash] opts the optional parameters
  # @option opts [GetListSchema] :q 
  # @return [InlineResponse20042]
  describe 'api_v1_report_pk_log_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_pk_log_log_id_get
  # Get a report schedule log
  # @param pk The report schedule pk for log
  # @param log_id The log pk
  # @param [Hash] opts the optional parameters
  # @option opts [GetItemSchema] :q 
  # @return [InlineResponse20043]
  describe 'api_v1_report_pk_log_log_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_pk_put
  # Update a report schedule
  # @param body Report Schedule schema
  # @param pk The Report Schedule pk
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20041]
  describe 'api_v1_report_pk_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_post
  # Create a report schedule
  # @param body Report Schedule schema
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20113]
  describe 'api_v1_report_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_report_related_column_name_get
  # @param column_name 
  # @param [Hash] opts the optional parameters
  # @option opts [GetRelatedSchema] :q 
  # @return [RelatedResponseSchema]
  describe 'api_v1_report_related_column_name_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
