=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SecurityApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SecurityApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SecurityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecurityApi' do
    it 'should create an instance of SecurityApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SecurityApi)
    end
  end

  # unit tests for api_v1_security_csrf_token_get
  # Fetch the CSRF token
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20047]
  describe 'api_v1_security_csrf_token_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_security_guest_token_post
  # Fetches a guest token
  # @param body Parameters for the guest token
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20048]
  describe 'api_v1_security_guest_token_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_security_login_post
  # Authenticate and get a JWT access and refresh token
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20049]
  describe 'api_v1_security_login_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_security_refresh_post
  # Use the refresh token to get a new JWT access token
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20050]
  describe 'api_v1_security_refresh_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
