=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::AllOfChartDataQueryObjectExtras
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfChartDataQueryObjectExtras' do
  before do
    # run before each test
    @instance = SwaggerClient::AllOfChartDataQueryObjectExtras.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfChartDataQueryObjectExtras' do
    it 'should create an instance of AllOfChartDataQueryObjectExtras' do
      expect(@instance).to be_instance_of(SwaggerClient::AllOfChartDataQueryObjectExtras)
    end
  end
  describe 'test attribute "druid_time_origin"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "having"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "having_druid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "relative_end"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["today", "now"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.relative_end = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "relative_start"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["today", "now"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.relative_start = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "time_grain_sqla"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PT1S", "PT5S", "PT30S", "PT1M", "PT5M", "PT10M", "PT15M", "PT30M", "PT1H", "PT6H", "P1D", "P1W", "P1M", "P3M", "P1Y", "1969-12-28T00:00:00Z/P1W", "1969-12-29T00:00:00Z/P1W", "P1W/1970-01-03T00:00:00Z", "P1W/1970-01-04T00:00:00Z"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.time_grain_sqla = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "time_range_endpoints"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "where"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
