=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ChartDataContributionOptionsSchema
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ChartDataContributionOptionsSchema' do
  before do
    # run before each test
    @instance = SwaggerClient::ChartDataContributionOptionsSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChartDataContributionOptionsSchema' do
    it 'should create an instance of ChartDataContributionOptionsSchema' do
      expect(@instance).to be_instance_of(SwaggerClient::ChartDataContributionOptionsSchema)
    end
  end
  describe 'test attribute "orientation"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["row", "column"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.orientation = value }.not_to raise_error
      # end
    end
  end

end
