=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ChartDataAdhocMetricSchema
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ChartDataAdhocMetricSchema' do
  before do
    # run before each test
    @instance = SwaggerClient::ChartDataAdhocMetricSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChartDataAdhocMetricSchema' do
    it 'should create an instance of ChartDataAdhocMetricSchema' do
      expect(@instance).to be_instance_of(SwaggerClient::ChartDataAdhocMetricSchema)
    end
  end
  describe 'test attribute "aggregate"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AVG", "COUNT", "COUNT_DISTINCT", "MAX", "MIN", "SUM"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.aggregate = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "column"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "expression_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SIMPLE", "SQL"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.expression_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "has_custom_label"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "is_extra"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "option_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "sql_expression"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "time_grain"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
