=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::DashboardPermalinkPostSchema
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DashboardPermalinkPostSchema' do
  before do
    # run before each test
    @instance = SwaggerClient::DashboardPermalinkPostSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DashboardPermalinkPostSchema' do
    it 'should create an instance of DashboardPermalinkPostSchema' do
      expect(@instance).to be_instance_of(SwaggerClient::DashboardPermalinkPostSchema)
    end
  end
  describe 'test attribute "filter_state"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hash"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "url_params"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
