=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::DatabaseSchemasQuerySchema
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DatabaseSchemasQuerySchema' do
  before do
    # run before each test
    @instance = SwaggerClient::DatabaseSchemasQuerySchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DatabaseSchemasQuerySchema' do
    it 'should create an instance of DatabaseSchemasQuerySchema' do
      expect(@instance).to be_instance_of(SwaggerClient::DatabaseSchemasQuerySchema)
    end
  end
  describe 'test attribute "force"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
