=begin
#Superset

#Superset

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.40
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::GetItemSchema
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetItemSchema' do
  before do
    # run before each test
    @instance = SwaggerClient::GetItemSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetItemSchema' do
    it 'should create an instance of GetItemSchema' do
      expect(@instance).to be_instance_of(SwaggerClient::GetItemSchema)
    end
  end
  describe 'test attribute "columns"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "keys"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["show_columns", "description_columns", "label_columns", "show_title", "none"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.keys = value }.not_to raise_error
      # end
    end
  end

end
